# Generated by Django 4.2.2 on 2023-06-30 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviaticketsinfo',
            options={'verbose_name': 'Ticket Info', 'verbose_name_plural': 'Avia tickets info'},
        ),
        migrations.AlterModelOptions(
            name='flyingfrom',
            options={'verbose_name': 'Airport', 'verbose_name_plural': 'Flying From'},
        ),
        migrations.AlterModelOptions(
            name='flyingto',
            options={'verbose_name': 'Airport', 'verbose_name_plural': 'Flying To'},
        ),
        migrations.AddField(
            model_name='aviaticketsinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
