# Generated by Django 4.2.2 on 2023-06-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_aviaticketsinfo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviaticketsinfo',
            old_name='date',
            new_name='search_date',
        ),
    ]
